namespace AlbionPacketExplorer.PhotonWire;

// GpBinary (Photon v18) value type tags. These byte values are facts of the Photon wire format
// (defined by Exit Games), not anyone's authored expression. Independent implementation.
internal enum GpType : byte
{
    Unknown = 0,
    Boolean = 2,
    Byte = 3,
    Short = 4,
    Float = 5,
    Double = 6,
    String = 7,
    Null = 8,
    CompressedInt = 9,
    CompressedLong = 10,
    Int1 = 11,
    Int1Neg = 12,
    Int2 = 13,
    Int2Neg = 14,
    Long1 = 15,
    Long1Neg = 16,
    Long2 = 17,
    Long2Neg = 18,
    Custom = 19,
    Dictionary = 20,
    Hashtable = 21,
    ObjectArray = 23,
    OperationRequest = 24,
    OperationResponse = 25,
    EventData = 26,
    BooleanFalse = 27,
    BooleanTrue = 28,
    ShortZero = 29,
    IntZero = 30,
    LongZero = 31,
    FloatZero = 32,
    DoubleZero = 33,
    ByteZero = 34,
    Array = 64,
    BooleanArray = 66,
    ByteArray = 67,
    ShortArray = 68,
    FloatArray = 69,
    DoubleArray = 70,
    StringArray = 71,
    CompressedIntArray = 73,
    CompressedLongArray = 74,
    CustomArray = 83,
    DictionaryArray = 84,
    HashtableArray = 85,
    CustomSlim = 128,
}
